### ISSUE TITLE
Delete submission is not triggering a leaderboard refresh?

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#1040]
To be investigated

**Comment by scarroll32** [comment]
Seems to be working OK for me. Closed.

**Comment by bednarikjan** [comment]
The issue still persists, I've just tried within the following challenge: https://www.crowdai.org/challenges/epfl-ml-road-segmentation.

**Steps:**
1) Submissions -> Create submission -> Upload file and confirm
![01_submission](https://user-images.githubusercontent.com/5279482/47563406-0624f180-d922-11e8-81db-3d1c30bf3cdf.png)
![02_leaderboard](https://user-images.githubusercontent.com/5279482/47563407-06bd8800-d922-11e8-9ef2-cc3c4af33e60.png)

2) Delete Submissions
- The submission disappears from the list of submissions (expected behaviour)
![03_deleted_submission](https://user-images.githubusercontent.com/5279482/47563451-281e7400-d922-11e8-8dff-68bfcee07325.png)

3) Leaderboard
- The entry is still there.
- If one clicks on the link within Entries column, a 500 error page appears.
![04_leaderboard_still_there](https://user-images.githubusercontent.com/5279482/47563518-58fea900-d922-11e8-9c2b-61af9833ccd7.png)
![05_error_500](https://user-images.githubusercontent.com/5279482/47563519-58fea900-d922-11e8-9ebf-d958f76215e2.png)

**Comment by scarroll32** [comment]
OK, I've found the root cause: this issue occurs when the last submission has been deleted, and then [this code](https://github.com/crowdAI/crowdai/blob/master/app/services/calculate_leaderboard_service.rb#L11) causes the process to exit.

When this line is removed, downstream code fails due to the inability to find a submission to calculate the [window](https://github.com/crowdAI/crowdai/blob/master/doc/leaderboard.md), and other downstream code will also fail.

It seems the best thing to do is to delete the leaderboard when the last submission has been deleted ... but I will need to think about this a bit.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/pull/1043/commits/52e4eff3e431e53dcf9affdb4689d290d65598f4

**Comment by scarroll32** [comment]
Implemented. Thank you @bednarikjan for the detailed bug report. For the entries left in the existing leaderboards, a one-time cleanup will be to add a submission, then delete it. 

That will clear the leaderboards without needing to access the back-end directly.
