### ISSUE TITLE
Disabling checkbox "Receive a daily digest email" doesn't work (keeps sending daily digests)

### ISSUE THREAD

**Issue by mar-muel** [crowdAI/crowdai#333]

**Comment by scarroll32** [comment]
Actually you've found a bug. The top 3 boxes define what emails will be sent. The bottom three are actually radio buttons, and only one must be on at any given time. Not sure how none is possible.

<img width="522" alt="screen shot 2017-10-05 at 10 38 49" src="https://user-images.githubusercontent.com/11340230/31218051-65927474-a9b9-11e7-8606-8b9fae073bbc.png">

Will also add additional code so that if no emails are selected, the bottom boxes are not selectable.

**Comment by scarroll32** [comment]
Should be OK now.
