### ISSUE TITLE
Clef Task instructional text

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#420]
When a participant reviews a clef task, there are a number of participant / task states possible, and the dataset download page will have different content depending on the state.

The states are:

- profile_incomplete: user has not completed the required profile fields (address etc)
- unregistered: user has completed fields but has not downloaded the EUA. Page displays the EUA download / upload
- requested: user has downloaded but not uploaded the completed EUA. Page displays the EUA download / upload
- submitted: user has uploaded the EUA but it has not been approved by the organizer. Approval pending message is displayed.
- registered: user has been approved and may download files. Files are listed for download.

**For each of these states, we need some instructional text.** 

<img width="1219" alt="screen shot 2017-11-14 at 11 16 22" src="https://user-images.githubusercontent.com/11340230/32774714-768b3386-c92d-11e7-953f-9c526a2f46ab.png">

**Comment by scarroll32** [comment]
For LifeCLEF the participant must complete the profile fields, but then may immediately download the data files. 

A message like "by downloading these files you agree to the terms and conditions " is displayed. This is configurable at the challenge level.

- profile_incomplete: user has not completed the required profile fields (address etc)
- registered: user has been approved and may download files. Files are listed for download.

**Comment by ieggel** [comment]
@seanfcarroll 
Here the instructional text for each of the **ImageCLEF** states:

**1. profile_incomplete**

This challenge belongs to the ImageCLEF lab which in turn is part of the Conference and Labs of the Evaluation Forum: CLEF 2018. In order to be compliant with the CLEF registration requirements, please edit your profile by providing the following information:

- First name

- Last name

- Affiliation

- Address

- City

- Country

- Regarding the username, please choose a name that represents your team

This information will not be publicly visible (except the username) and will be exclusively used to contact you and to send the registration data to CLEF, which is the main organizer of all CLEF labs.

After the completion of this information, you will be asked to fill in and sign an End User Agreement (EUA) document.

**2. unregistered**

In order to get access to the dataset in this challenge you have to fill in and sign an End User Agreement (EUA) document. 
Please do the following steps:

- Download the EUA document and print it

- Fill in the required information in the EUA document and sign it

- Scan and re-upload the EUA document

After the approval of your completed EUA document by an ImageCLEF organizer, you will get access to the dataset. You will also be automatically registered with CLEF, the main organizer of all CLEF labs.

**3. requested**

In order to get access to the dataset in this challenge you have to sign an End User Agreement (EUA). 
You have previously downloaded the EUA document. Please do now the following steps:

- Print the EUA document

- Fill in the required information in the EUA document and sign it

- Scan and re-upload the EUA document

After the approval of your completed EUA document by an ImageCLEF organizer, you will get access to the dataset. You will also be automatically registered with CLEF, the main organizer of all CLEF labs.

**4. submitted**

The approval of your completed End User Agreement (EUA) document is pending. As soon as an ImageCLEF organizer approves the document, you will get access to the dataset.

In case you want replace a faulty completed EUA document, just re-upload a new one.

After the approval of your completed EUA document by an ImageCLEF organizer, you will get access to the dataset. You will also be automatically registered with CLEF, the main organizer of all CLEF labs.

**5. registered**

Your sigend End User Agreement (EUA) has been approved. You are allowed to access this challenge's dataset.

**Comment by ieggel** [comment]
@seanfcarroll 
Here the instructional text for each of the **LifeCLEF** states:

**1. profile_incomplete**:

This challenge belongs to the LifeCLEF lab which in turn is part of the Conference and Labs of the Evaluation Forum: CLEF 2018. In order to be compliant with the CLEF registration requirements, please edit your profile by providing the following information:

- First name

- Last name

- Affiliation

- Address

- City

- Country

- Regarding the username, please choose a name that represents your team

This information will not be publicly visible (except the username) and will be exclusively used to contact you and to send the registration data to CLEF, which is the main organizer of all CLEF labs.

**2. registered**:

You have filled in all required information in your profile. Therefore you are allowed to access this challenge's dataset.

**Comment by scarroll32** [comment]
Implemented
