### ISSUE TITLE
video icon needs to be removed

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#453]
from non-video challenges - a very confusing user experience:

<img width="152" alt="screen shot 2017-11-27 at 16 05 19" src="https://user-images.githubusercontent.com/215057/33273217-e85b75c0-d38c-11e7-9d97-4bffc359a3dc.png">

i.e. on the NIPS workshop challenge, the music challenge, etc...

**Comment by spMohanty** [comment]
Actually these are supposed to take the user to a generic submission page. Which has more details about the submission.
Instead of removing them, I would simply link them to the correct page about the submission.

In the absence of media, it could be simple meta data about the submission, available scores, etc.

In case of the music challenge, I can very quickly implement a player for the whole song (1hour) which can be rendered as a react component here. But depends on if we want to deal with this issue now, or later.

**Comment by marcelsalathe** [comment]
We don't, so for now I would remove it. Also on the other challenges where it is.

**Comment by scarroll32** [comment]
Driving it from the "media on leaderboard" setting on the challenge.

**Comment by scarroll32** [comment]
Implemented.
