### ISSUE TITLE
Text for challenge calls

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#491]
Some suggested changes:

Describe the task and general overview of the way the challenge will be run.
->
Give a general overview of the challenge, what problem it should solve, and how it will be run.

Why should the challenge be hosted on crowdAI?
->
Impact of the challenge

Describe why the challenge should be hosted on crowdAI, including assessment of the significance of the task and of the potential impact of the challenge. This should also include a brief overview of existing work in the area of the challenge (e.g. what is the current baseline solution to the problem addressed, which research groups are doing research in this area and can be expected to participate in the challenge).
->
Explain the significance of the task and describe the potential impact of the challenge. Please also provide a brief overview of existing work in the area of the challenge, and describe the current baseline solution to the problem addressed. How can the challenge improve this baseline?

Briefly describe the structure of the challenge, including what is being submitted by participants when (e.g. solution software, evaluation results), and what is being provided by the organisers when (e.g. benchmark data, evaluation framework).
->
Describe the structure of the challenge, i.e. what (if anything) do you provide in terms of data and evaluation framework, and what do the participants have to submit?

A clear description of the way the evaluation will be conducted, i.e. what will be measured, in what way, and for what purpose. Qualitative evaluations are acceptable, but challenge organisers will have to explain how such an evaluation can be used as a basis to assess the solutions proposed by challenge participants against each other.
->
How will the submissions be evaluated, and why? Please give as much detail as possible - this is usually where most of the work lies, and a clear evaluation scheme helps a lot.

Organiser bio(s)
Please add a short bio of each of the organisers in relation to the challenge.
-> I think this field can be removed

Please indicate here if you will need specific resources for the organisation of the challenge, and if you already have plans regarding prizes or sponsors for your challenge. Also indicate if the challenge is part of a series of challenges, is related to another event (e.g. an existing workshop) or to a project.
->
What prizes can you provide for the winners of the challenge? Do you have additional sponsorships secured? Is this challenge part of a workshop, a series, or anything else that is important to know?

@spMohanty please chime in - these will be fields for all future calls, so this is the moment to ask the right questions!

**Comment by spMohanty** [comment]
PS: Sorry for the formatting. typing this out on my smartphone; and will fix the formatting when i get back to my laptop.

Hi @marcelsalathe,

Here are some of the changes I would suggest : 

---
Why should the challenge be hosted on crowdAI?
->
Impact of the challenge

This question is redundant ? the next questions asks the same thing, in a more expressive way. or am I getting something wrong ?
---
---
Briefly describe the structure of the challenge, including what is being submitted by participants when (e.g. solution software, evaluation results), and what is being provided by the organisers when (e.g. benchmark data, evaluation framework).
->
Describe the structure of the challenge, i.e. what (if anything) do you provide in terms of data and evaluation framework, and what do the participants have to submit?

---
I would change this line from : "what (if anything) do you provide in terms of data and evaluation framework, and what do the participants have to submit?" to : "what do you provide in terms of data (if anything) and evaluation framework, and what do the participants have to submit?"

as they have to provide an evaluation framework in any case for every challenge. the data is optional.
---
---
Organiser bio(s)
Please add a short bio of each of the organisers in relation to the challenge.
-> I think this field can be removed
---
I think we should still keep this field, to get a sense of the team vouching for it. in case of a large number of requests, it might help us prioritize challenges based on the experience of the team. Can be change to "Organiser details", where we collect just Organiser names and affiliations instead of the bio.
---

**Comment by marcelsalathe** [comment]
Taking @spMohanty's points into account, here are the new changes:

Describe the task and general overview of the way the challenge will be run.
->
Give a general overview of the challenge, what problem it should solve, and how it will be run.

Why should the challenge be hosted on crowdAI?
->
Impact of the challenge

Describe why the challenge should be hosted on crowdAI, including assessment of the significance of the task and of the potential impact of the challenge. This should also include a brief overview of existing work in the area of the challenge (e.g. what is the current baseline solution to the problem addressed, which research groups are doing research in this area and can be expected to participate in the challenge).
->
Explain the significance of the task and describe the potential impact of the challenge. Please also provide a brief overview of existing work in the area of the challenge, and describe the current baseline solution to the problem addressed. How can the challenge improve this baseline?

Briefly describe the structure of the challenge, including what is being submitted by participants when (e.g. solution software, evaluation results), and what is being provided by the organisers when (e.g. benchmark data, evaluation framework).
->
Describe the structure of the challenge, i.e. what (if anything) do you provide in terms of data, and what do you provide in terms of the evaluation framework? What do the participants have to submit?

A clear description of the way the evaluation will be conducted, i.e. what will be measured, in what way, and for what purpose. Qualitative evaluations are acceptable, but challenge organisers will have to explain how such an evaluation can be used as a basis to assess the solutions proposed by challenge participants against each other.
->
How will the submissions be evaluated, and why? Please give as much detail as possible - this is usually where most of the work lies, and a clear evaluation scheme helps a lot.

Organiser bio(s)
--> Organizer details
Please tell us something about the organizer(s), in particular with respect to the challenge? Have you already run challenges before?

Please indicate here if you will need specific resources for the organisation of the challenge, and if you already have plans regarding prizes or sponsors for your challenge. Also indicate if the challenge is part of a series of challenges, is related to another event (e.g. an existing workshop) or to a project.
->
What prizes can you provide for the winners of the challenge? Do you have additional sponsorships secured? Is this challenge part of a workshop, a series, or anything else that is important to know?

**Comment by scarroll32** [comment]
Implemented.
