### ISSUE TITLE
Background image missing on landing page

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#573]

**Comment by jsnrynlds** [comment]
@seanfcarroll Not sure why this isn't visible. Image is attached to `#home` and appears in the CSS when I inspect the div in Chrome...

**Comment by spMohanty** [comment]
@seanfcarroll : Could it be this : https://stackoverflow.com/questions/22169934/cloudfront-on-rails-not-showing-new-images ?
```
I found the problem. Sometime between the precompile and the restart of the server 
someone made a request and Cloudfront couldn't find the image so that's why it wasn't 
showing. I changed the image name, re-depoyed it and everything is fine now.
```

**Comment by spMohanty** [comment]
This was happening because of this line : https://github.com/crowdAI/crowdai/blame/master/app/views/landing_page/index.html.erb#L1

Where the `content` tag has been used. Not sure the exact reason why it was used, but the tag is in any case deprecated (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content).

Sending a pull request which fixes this.

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/42cbc9ca059f9e3de8b5cda40c54dc80588d0ed7
