### ISSUE TITLE
500 on leaderboard in a new challenge

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#668]
@seanfcarroll : When we create a new challenge, and then go to the leaderboard, it throws a 500.
I dont remember exactly, but I think this is usually fixed by adding a "round" (?)

In any case, its a bit irritating, and I think just creating a new challenge should work out of the box, and all the necessary configurations/fields should be added by default with some predecided default values.

For instance, if the rounds thing is indeed an issue, then on creation of a challenge, we can add a round starting on the day of the creation of the challenge, and ending say 3 months after that.
Same for any other confrontational details.

**Comment by scarroll32** [comment]
The challenge needs a round and also needs to be made active. You can also disable the "leaderboard active' checkbox if it is not live. Is there a specific challenge that is causing this problem?

I agree, there are **many** things that need fixing in crowdAI. The code base has been hacked and patched aggressively for many months now, and it needs a refactor and updated test coverage. The problem is finding time to do this whilst also adding new features and launching challenges at the current pace. 

I suggest we keep opening issues for any problems, marking them as high if they cannot wait. I am generally working issues in order of:

1. Bug + high
2. New feature + high
3. Bug + not high
4.  Others

In practice, new features for upcoming challenges are usually pushed to the top of the list.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/issues/619
