### ISSUE TITLE
Submission web page check for permission

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#681]
If a participant knows the submission URL he/she can submit with no checks performed at all, i.e. not checked if registered and not checked if challenge is running etc.

In order to decide if "Create submission" button is shown or not, the following code was used:
`    <% if submissions_allowed?(challenge) && current_tab != 'dataset'%>
      <%= link_to 'Create Submission',
            new_challenge_submission_path(challenge),
            class: "btn btn-secondary pull-right" %>
    <% end %>`

@seanfcarroll Would you mind having a look?

**Comment by ieggel** [comment]
I also noticed that the submission button is now shown always and a permission check does not seem to be performed. This actually used to work on Friday. Was anything changed here?
Below a screenshot. Participant is not registered for the task (as you can see did not sign the EUA) but still sees the submission button:
![image](https://user-images.githubusercontent.com/9192090/38562886-e802c818-3cdb-11e8-9500-d4969526feab.png)

@seanfcarroll

**Comment by scarroll32** [comment]
Hi @ieggel yes it did change, a couple of times, since Friday as there was clef code affecting non-clef challenges. really we need to write tests for all of this, but in the meantime the code in question is [here](https://github.com/crowdAI/crowdai/blob/master/app/helpers/submissions_helper.rb#L20-L53) 

If the **submissions_allowed?** method returns true the button is visible. It looks OK to me, so could it be a data issue  ( **return true if participant_clef_task.registered?** ) ? 

 If you can see the logic error let me know here or make a PR. 

As you can see, there are many branches to write tests against here. It will also change again when we implement https://github.com/crowdAI/crowdai/issues/535

**Comment by spMohanty** [comment]
I would also add that in case of all upstream changes we should try to avoid having exceptions as much as we can. Meaning all the features we develop we try to make it more generic for crowdai, and make it configurable so that clef can use it. The dev process will be slower, but the code will be much more managable in the long term, and will save us all a lot of headaches too in the long run. 
We can start by having a separate issue for merging all the clef specific code in a more generalisable way to the rest of the crowdai codebase.

**Comment by ieggel** [comment]
HI @seanfcarroll 

I can spot an issue here. Actually if the challenge is running, anyone can see the submission button because the clef checks are performed later only.

`    if challenge.running?
      return true
   `

**Comment by scarroll32** [comment]
Code migrated to production but untested. Leaving this issue open + high so that test cases can be written.

https://github.com/crowdAI/crowdai/commit/c59201b20b716d3254f0f8a1405ad817e982130e

@ieggel if you have time, it would be awesome if you could write some helper tests for this. Some information on how to do this is [here](https://stackoverflow.com/questions/1996757/writing-a-spec-for-helper-with-ruby-on-rails-and-rspec)

The secondary issue is that the path is still available via direct url. In fact this whole thing can be moved into Pundit.

**Comment by ieggel** [comment]
Thanks @seanfcarroll 
It's working.
It is also very important that participants cannot access the URL. I will have a look.

**Comment by ieggel** [comment]
@seanfcarroll 
The permission issue should have been resolved with PR #689. 
Regarding tests: i currently very busy, but we should discuss this once in more depth.
