### ISSUE TITLE
Unable to log in after signing up 

### ISSUE THREAD

**Issue by SnigdhaD** [crowdAI/crowdai#696]
![screen shot 2018-04-13 at 22 12 09](https://user-images.githubusercontent.com/8699002/38755965-09df8e10-3f68-11e8-860f-6103cd3da235.png)

**Comment by spMohanty** [comment]
I think you need to follow the instructions in the signup confirmation email that you should have received. But yeah, the error message should be more informative.

**Comment by scarroll32** [comment]
There is a "Can't log in?" link on the login page

<img width="525" alt="screen shot 2018-05-04 at 15 24 16" src="https://user-images.githubusercontent.com/11340230/39630309-46c9f9da-4faf-11e8-8465-0b55ad7a780c.png">
<img width="526" alt="screen shot 2018-05-04 at 15 24 51" src="https://user-images.githubusercontent.com/11340230/39630326-4fb38c14-4faf-11e8-8d61-1b551ea8c9ee.png">

**Comment by spMohanty** [comment]
No, if I remember correctly, 
this issue was when she signed up,
and was trying to log in.

But she couldnt log in because she hadnt yet clicked on the confirmation email.

Basically, the behaviour is correct, the error message should be more informative. 
Something like : 

"Account not verified. You have to first verify your account by clicking on the link provided in the confirmation email sent to your email".

**Comment by scarroll32** [comment]
We do flash a message, I think it's pretty clear. Then there are options to resend the email on the login page.

<img width="1087" alt="screen shot 2018-05-08 at 15 53 18" src="https://user-images.githubusercontent.com/11340230/39761290-006b51d8-52d8-11e8-9f9f-e1accdfcb817.png">

**Comment by scarroll32** [comment]
I'll increase the message duration - 5s to 10s.
