### ISSUE TITLE
CLEF Webpage submission highlight mandatory fields

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#697]
HI @seanfcarroll 

Is there a common way to highlight mandatory fields for forms?
The following fields are mandatory are mandatory in the CLEF submission webpage:
- Method description (Text area)
- Retrieval type (Dropdown) with following values:
- Run type (Dropdown)

**Comment by scarroll32** [comment]
The design of crowdAI did not include the '*' sometimes used to indicate required field. You could instead of adding a subtext. See 'views/challenges/form/_details' for an example.

```  <span>Your image will be cropped if necessary. 5MB limit</span>```

In any case if validations are present on the model, an error message will appear. See below.

<img width="518" alt="screen shot 2018-04-16 at 17 01 03" src="https://user-images.githubusercontent.com/11340230/38817065-d95e49d4-4197-11e8-8f0a-31a39bb4e16e.png">
<img width="601" alt="screen shot 2018-04-16 at 16 59 57" src="https://user-images.githubusercontent.com/11340230/38817066-d978dcb8-4197-11e8-9636-52c8cd6937f0.png">

**Comment by ieggel** [comment]
Thanks @seanfcarroll 

I will have a look.
