### ISSUE TITLE
Don't increase submission count if submission faulty

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#708]
Hi all,

I often get asked why faulty submissions count towards the maximum nbr of submissions limit and to be honest i cannot see a reason either. I understand there should be a total nbr of allowed submissions as otherwise people could intentionally send countless faulty submissions to overload the system.

Maybe it would be a good idea to have:
- Total submission limit (nbr of valid + nbr of faulty submissions)
- Valid submission limit

In that case we could then e.g. set:
- Total submission limit = 15
- Valid submission limit = 10

In this example this would leave room for 5 (15 - 10) faulty submissions.

Just wanted to hear your opinion on that matter.

**Comment by spMohanty** [comment]
The limit on the number of total submissions is for us to put an upper bound on the total computational resources that we should allot towards a challenge.
Each faulty submission can in principle take the same amount of computational resources as valid one, and hence we went with a fixed limit of submissions.

But I agree, I can also see use cases where we would want to have limits on both correct submissions and faulty submissions.

**Comment by scarroll32** [comment]
Could be handled with a new config param, would need some extensive testing to ensure it doesn't break existing behaviour.

**Comment by scarroll32** [comment]
Allow N faulty submissions per period set for submissions.

**Comment by scarroll32** [comment]
Postponed to August.

**Comment by scarroll32** [comment]
I'm not sure about this one - the whole leaderboard / grading calculation is already way too complicated. I suggest we don't proceed with this. @spMohanty thoughts?

**Comment by scarroll32** [comment]
Closing due to lack of interest.

**Comment by spMohanty** [comment]
Hi @seanfcarroll,

I think we had verbally discussed this at some point. But the conclusion was that this is an important request we get all the time; but it is low
Priority for us at the miment, because you said the implementation would be tricky. 

In an ideal world; every challenge will be two submission limits : successful submissions max limit: and failed submissions max limit. 

If the number of successful submissions are done for the day, then no submissions will be allowed. 

If the number of failed max submissions are done for the day, then subsequent failures will start using the quota from the max number of successful submissions.

**Comment by scarroll32** [comment]
Upgraded to high as needed for  AI for Prosthetics challenge, sept 24th

**Comment by MasterScrat** [comment]
There should also be seperate handling between a submission that failed because of user mistake vs a problem in the grading infrastructure. 

Eg repo cloning problems shouldn't count as submissions. Same thing for timeout of pods that didn't get a chance to run at all.

**Comment by scarroll32** [comment]
This issue was scheduled to be done by Sept 24th, but can be fast-tracked. It needs careful testing as the code is already pretty complicated and it will affect every challenge. 

However, the original request was to allow for a participant-initiated error buffer. When the errors are system errors, I agree they should not be applied to the user.

In that case I think we should have a new error type : 'system error', which the grader would need to mark as such. Any instances of this error would not apply to either the submission count or the participant-error count.

Does that work @MasterScrat  ?

**Comment by scarroll32** [comment]
Incidentally, if a user is receiving errors because their repo is too large, perhaps that should be considered a user error. But in that case we should nominate that as an error message "repo is too large", and detail a solution in a FAQ. 

It would also be possible to make error messages a link to a FAQ. So far our FAQ is only this: https://www.crowdai.org/faq

This also relates to having documentation.

**Comment by MasterScrat** [comment]
> However, the original request was to allow for a participant-initiated error buffer. When the errors are system errors, I agree they should not be applied to the user.

Ok so actually this could be made into 2 different issues.

> In that case I think we should have a new error type : 'system error', which the grader would need to mark as such. Any instances of this error would not apply to either the submission count or the participant-error count.

@seanfcarroll yes that would make sense!

Regarding repo size we should actually check it before attempting to clone, because trying to clone an oversized repo uses a lot of resources before it eventually fails.

**Comment by scarroll32** [comment]
Implemented
