### ISSUE TITLE
Inconsistency in "submission counts remaining"

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#716]
this was a report from one of the users : 
```
Actually I tried to make new submission but got the error “The participant has no submission slots remaining for today.” It was only second submission made today, so I suspect it could be an error in system. 
my nick on crowd.ai is kvr
```
This was in context of the IEEE Investment ranking challenge. Can confirm that the challenge has a limit of 5 submissions per day for this round, and the participant has made only 1 submissions in the last 24 hours.

**Comment by scarroll32** [comment]
Is it possible to provide the username and challenge?

**Comment by spMohanty** [comment]
@seanfcarroll : The challenge is : https://www.crowdai.org/challenges/ieee-investment-ranking-challenge
and the user is : https://www.crowdai.org/participants/kvr

**Comment by AALEKH** [comment]
As already mentioned in Gitter channel, I have also experienced the same issue (username: aalekhn)

**Comment by AALEKH** [comment]
Hey guys, is there any update on this issue? I am still experiencing the same even though I haven't made any submission today (30/04/2018 GMT).

**Comment by scarroll32** [comment]
Hi all, I've reviewed the code on this and it is indeed working OK. The possible confusion is that 'day' refers to a 24 hour window, ie: how many submissions have been made from Now - 24 hours. So this could include submissions made against yesterday's calendar date.

There are some new documents on this here : https://github.com/crowdAI/crowdai/blob/master/doc/submission_limits.md

We will provide more information to the Python client about the previous submissions made, probably quite soon.

**Comment by spMohanty** [comment]
One of the participants who had complained, had made a total of 3 submissions in the whole challenge (and on crowdAI too), and he was getting a submission limit reached on a challenge with 5 submissions per day limit. 
I think it was kvr or alekh ?

**Comment by scarroll32** [comment]
@AALEKH is it also the IEEE challenge?

**Comment by scarroll32** [comment]
I'll pull the database and try to replicate the error. Before I start though, we are on a new round in IEEE, which started on 3/5 and has a limit of 10 / day. Is it still a problem?

**Comment by AALEKH** [comment]
@seanfcarroll @spMohanty  Yup I was referring to IEEE challenge; of course python client update will be super helpful. I would also like to point out that  there seems to be an issue with submission since the start of round 2, my submission attempt via script mentioned in starter's kit happens to get stuck every time at this state:
`CrowdAI.Event.Authentication : Authenticating for challenge = IEEEInvestmentRankingChallenge
CrowdAI.Event.Connection.CONNECTED
CrowdAI.Event.Authentication.SUCCESS : Authentication Successful
CrowdAI.Event.Misc.FILE_UPLOAD : Preparing for file upload
CrowdAI.Event.Misc.FILE_UPLOAD : Uploading file
100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|[00:07<00:00]  13.74% /s]
  0% |                                                                                                                                                            |[00:00<?]  ?% /s]
`

For this reason I and probably many others (since round 2 leaderboard and submission dashboard seems to be empty) are not able to submit any of our predictions (for last many days). Apologies for reporting this late but it would be super helpful if this can be resolved since I would like to make an attempt by submitting a short paper with new predictions.

**Comment by scarroll32** [comment]
Can this issue be closed?

**Comment by scarroll32** [comment]
Closed
