### ISSUE TITLE
Round 1 button shown 2 times in Leaderboard view

### ISSUE THREAD

**Issue by mihahauke** [crowdAI/crowdai#775]
Like in the title. It doesn't look like intended. It could be seen in [https://www.crowdai.org/challenges/visual-doom-ai-competition-2018-track-1/leaderboards](https://www.crowdai.org/challenges/visual-doom-ai-competition-2018-track-1/leaderboards)
![screenshot from 2018-05-08 17-43-39](https://user-images.githubusercontent.com/2771069/39767684-9eaee51c-52e7-11e8-82a4-2bff86e0ed5b.png)

**Comment by spMohanty** [comment]
@seanfcarroll : Can you have a look at this one ? 
This is a small bug, but very confusing (and irritating too :cry: ).

**Comment by scarroll32** [comment]
Yes, it is annoying. This is caused by a UI issue in the challenge round configuration. It can be addressed temporarily by making sure only 1 round is marked as 'current round". (I've set the first round on this challenge as the current round now).

I'll fix this properly as part of the current refactor. 

<img width="793" alt="screen shot 2018-05-08 at 18 15 05" src="https://user-images.githubusercontent.com/11340230/39769234-eb07c7cc-52eb-11e8-8ece-502ddb6f31ef.png">

**Comment by spMohanty** [comment]
Thanks Sean for the quick response,
Cheers,
Mohanty
