### ISSUE TITLE
Create DB seeds

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#908]
@spMohanty :

Now that Florian has done the Dockerizing, I will create some non-sensitive seed data.
I was thinking to take 2 challenges and reduce the submissions and participants and anonymise it all
How does plant village as a predictions / job factory and vizdoom single player as a a gitlab based submission sound?
It was take some effort to clean the data, and then we should sync the data in the gitlab instance also, we can discuss this part.

**Comment by spMohanty** [comment]
@seanfcarroll : Instead of going with actual challenges, I would go with some of the template examples that we have.
We have the example evaluator for the job factory based grading.
And we also have a example contractor for the gitlab based grading approaches.

And both of the cases cover a very simple use cases, and the plan is to document them so that others can develop the said components themselves for their own challenges.

**Comment by scarroll32** [comment]
Done
